import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const p=JSON.parse(readFileSync(new URL('../auditorias/google-ads-ajustes-imediatos-2026-09-12/PLANO.json',import.meta.url),'utf8'));
const registry=readFileSync(new URL('./REGISTRO-CODIGOS-ATRIBUICAO.md',import.meta.url),'utf8');
test('pacote preserva oito orcamentos e R$103/dia',()=>{assert.equal(p.accountId,'995-334-4486');assert.equal(Object.keys(p.budgetByCampaign).length,8);assert.equal(Object.values(p.budgetByCampaign).reduce((a,b)=>a+b,0),103);});
test('parametros limitados a seis anuncios e codigos canonicos existentes',()=>{assert.equal(p.parameters.length,6);assert.equal(new Set(p.parameters.map(x=>x.adId)).size,6);for(const r of p.parameters){assert.match(r.adId,/^\d{12}$/);assert.match(r.adGroupId,/^\d{12}$/);assert.equal(r.after.camp,r.campaign);assert.ok(registry.includes(r.after.camp));assert.ok(registry.includes(r.after.ag));assert.deepEqual(Object.keys(r.after).sort(),['ag','camp']);}assert.equal(p.parameters.filter(x=>x.before.camp!==x.after.camp).length,5);assert.equal(p.parameters.filter(x=>x.before.ag!==x.after.ag).length,3);});
test('geografia restringe apenas LIFT/CERV e nao cria local ou aumenta verba',()=>{assert.deepEqual(p.geo.map(x=>x.campaignId).sort(),['24023843174','24028216444']);for(const r of p.geo){assert.equal(r.before,'PRESENCE_OR_INTEREST');assert.equal(r.after,'PRESENCE');assert.equal(r.location,'São Paulo, São Paulo, Brasil cidade');}assert.equal(p.geo.reduce((a,b)=>a+b.dailyBudgetBRL,0),36);});
test('importacao preserva identidade e nao amplia PII ou dispara lote',()=>{assert.equal(p.mapping.conversionActionId,'7697681883');assert.deepEqual(p.mapping.add,[{source:'GBRAID',destination:'GBRAID'},{source:'WBRAID',destination:'WBRAID'}]);assert.equal(p.mapping.runManually,false);assert.equal(p.mapping.consentChanges,false);assert.equal(p.mapping.enhancedConversions,false);assert.ok(p.excluded.includes('site'));assert.ok(p.excluded.includes('lances'));});
